# docker-compose.yml
version: '3.8'

services:
  log-generator:
    build: .
    container_name: log-generator
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
